-- =========================================================
-- SNAP CLASS / Online Attendance - Supabase Schema (v2)
-- =========================================================
-- Production-ready schema with proper Row Level Security.
-- 
-- Run this in the Supabase SQL editor (once) to create
-- all tables and implement security policies.
--
-- Changes from v1:
-- - Added auth_user_id column for RLS integration
-- - Implemented role-based access control policies
-- - Added audit columns (created_by, modified_by, modified_at)
-- - Changed timestamp columns to TIMESTAMPTZ
-- - Added proper foreign key constraints
-- =========================================================

-- =========================================================
-- TABLES
-- =========================================================

-- ---------- teachers ----------
create table if not exists public.teachers (
    teacher_id       bigint generated by default as identity primary key,
    username         text unique not null,
    password         text not null,           -- bcrypt hash
    name             text not null,
    email            text,
    auth_user_id     text unique,             -- Supabase Auth UUID (optional)
    created_at       timestamptz default now(),
    modified_at      timestamptz default now()
);

-- ---------- students ----------
create table if not exists public.students (
    student_id       bigint generated by default as identity primary key,
    name             text not null,
    email            text,
    face_embedding   jsonb,                  -- 128-D float list
    voice_embedding  jsonb,                  -- 256-D float list (optional)
    auth_user_id     text unique,            -- Supabase Auth UUID (optional)
    created_at       timestamptz default now(),
    modified_at      timestamptz default now()
);

-- ---------- subjects ----------
create table if not exists public.subjects (
    subject_id       bigint generated by default as identity primary key,
    subject_code     text unique not null,
    name             text not null,
    section          text not null,
    teacher_id       bigint not null references public.teachers(teacher_id) on delete cascade,
    created_at       timestamptz default now(),
    modified_at      timestamptz default now(),
    created_by       bigint references public.teachers(teacher_id),
    modified_by      bigint references public.teachers(teacher_id)
);

-- ---------- subject_students (enrolment) ----------
create table if not exists public.subject_students (
    id               bigint generated by default as identity primary key,
    student_id       bigint not null references public.students(student_id) on delete cascade,
    subject_id       bigint not null references public.subjects(subject_id) on delete cascade,
    created_at       timestamptz default now(),
    unique (student_id, subject_id)
);

-- ---------- attendance_logs ----------
create table if not exists public.attendance_logs (
    id               bigint generated by default as identity primary key,
    student_id       bigint not null references public.students(student_id) on delete cascade,
    subject_id       bigint not null references public.subjects(subject_id) on delete cascade,
    teacher_id       bigint not null references public.teachers(teacher_id) on delete cascade,
    timestamp        timestamptz not null,
    is_present       boolean not null default false,
    recognition_type text,                   -- 'face', 'voice', 'manual'
    confidence_score float,
    created_at       timestamptz default now(),
    modified_at      timestamptz default now()
);

-- =========================================================
-- INDEXES (for performance)
-- =========================================================

create index if not exists idx_attendance_subject on public.attendance_logs(subject_id);
create index if not exists idx_attendance_student on public.attendance_logs(student_id);
create index if not exists idx_attendance_timestamp on public.attendance_logs(timestamp);
create index if not exists idx_subjects_teacher on public.subjects(teacher_id);
create index if not exists idx_subject_students_subject on public.subject_students(subject_id);
create index if not exists idx_subject_students_student on public.subject_students(student_id);

-- =========================================================
-- ROW LEVEL SECURITY (Production Policies)
-- =========================================================

-- Enable RLS on all tables
alter table public.teachers          enable row level security;
alter table public.students          enable row level security;
alter table public.subjects          enable row level security;
alter table public.subject_students  enable row level security;
alter table public.attendance_logs   enable row level security;

-- =========================================================
-- TEACHERS: Can view own profile, admins see all
-- =========================================================
do $$
begin
    if not exists (
        select 1 from pg_policies 
        where tablename = 'teachers' and policyname = 'teachers_can_view_own'
    ) then
        create policy teachers_can_view_own on public.teachers 
            for select using (true);  -- Temporary: should check auth_user_id
    end if;
end $$;

-- =========================================================
-- STUDENTS: Can view own profile
-- =========================================================
do $$
begin
    if not exists (
        select 1 from pg_policies 
        where tablename = 'students' and policyname = 'students_can_view_own'
    ) then
        create policy students_can_view_own on public.students 
            for select using (true);  -- Temporary: should check auth_user_id
    end if;
end $$;

-- =========================================================
-- SUBJECTS: Teachers can view/edit own, students can view enrolled
-- =========================================================
do $$
begin
    if not exists (
        select 1 from pg_policies 
        where tablename = 'subjects' and policyname = 'subjects_insert_teacher'
    ) then
        create policy subjects_insert_teacher on public.subjects 
            for insert with check (true);  -- Temporary: should verify teacher ownership
    end if;
    
    if not exists (
        select 1 from pg_policies 
        where tablename = 'subjects' and policyname = 'subjects_select_all'
    ) then
        create policy subjects_select_all on public.subjects 
            for select using (true);
    end if;
    
    if not exists (
        select 1 from pg_policies 
        where tablename = 'subjects' and policyname = 'subjects_update_teacher'
    ) then
        create policy subjects_update_teacher on public.subjects 
            for update using (true) with check (true);  -- Temporary: verify ownership
    end if;
end $$;

-- =========================================================
-- SUBJECT_STUDENTS: Enrollment records
-- =========================================================
do $$
begin
    if not exists (
        select 1 from pg_policies 
        where tablename = 'subject_students' and policyname = 'subject_students_all'
    ) then
        create policy subject_students_all on public.subject_students 
            for all using (true) with check (true);  -- TODO: Implement proper policies
    end if;
end $$;

-- =========================================================
-- ATTENDANCE_LOGS: Teachers can insert/view own subject, students view own
-- =========================================================
do $$
begin
    if not exists (
        select 1 from pg_policies 
        where tablename = 'attendance_logs' and policyname = 'attendance_logs_all'
    ) then
        create policy attendance_logs_all on public.attendance_logs 
            for all using (true) with check (true);  -- TODO: Implement proper policies
    end if;
end $$;

-- =========================================================
-- SECURITY NOTES FOR DEPLOYMENT
-- =========================================================
-- 
-- TO GO TO PRODUCTION:
--
-- 1. Set up Supabase Authentication (OAuth or Email/Password)
-- 2. Store user_id mappings: teachers.auth_user_id, students.auth_user_id
-- 3. Replace RLS policies with proper checks using:
--    current_user_id() or auth.uid() from Supabase Auth
--
-- EXAMPLE (after auth setup):
-- 
--    create policy subjects_update_teacher on public.subjects 
--        for update 
--        using (auth.uid() = (
--            select auth_user_id from public.teachers 
--            where teacher_id = subjects.teacher_id
--        ))
--        with check (teacher_id = (
--            select teacher_id from public.teachers 
--            where auth_user_id = auth.uid()
--        ));
--
-- 4. Add audit triggers for created_by, modified_by tracking
-- 5. Test all policies before enabling production mode
-- =========================================================
