-- =========================================================
-- SNAP CLASS / Online Attendance - Supabase schema
-- =========================================================
-- Run this in the Supabase SQL editor (once) to create
-- all the tables the app needs.
--
-- IMPORTANT: this app uses Supabase as a plain database
-- (no Row Level Security checks). For a quick demo you can
-- run with RLS disabled; for production, add policies that
-- match your auth model.
-- =========================================================

-- ---------- teachers ----------
create table if not exists public.teachers (
    teacher_id  bigint generated by default as identity primary key,
    username    text unique not null,
    password    text not null,           -- bcrypt hash
    name        text not null,
    created_at  timestamptz default now()
);

-- ---------- students ----------
create table if not exists public.students (
    student_id       bigint generated by default as identity primary key,
    name             text not null,
    face_embedding   jsonb,              -- 128-D float list
    voice_embedding  jsonb,              -- 256-D float list (optional)
    created_at       timestamptz default now()
);

-- ---------- subjects ----------
create table if not exists public.subjects (
    subject_id    bigint generated by default as identity primary key,
    subject_code  text unique not null,
    name          text not null,
    section       text not null,
    teacher_id    bigint references public.teachers(teacher_id) on delete cascade,
    created_at    timestamptz default now()
);

-- ---------- subject_students (enrolment) ----------
create table if not exists public.subject_students (
    id          bigint generated by default as identity primary key,
    student_id  bigint references public.students(student_id) on delete cascade,
    subject_id  bigint references public.subjects(subject_id) on delete cascade,
    created_at  timestamptz default now(),
    unique (student_id, subject_id)
);

-- ---------- attendance_logs ----------
create table if not exists public.attendance_logs (
    id          bigint generated by default as identity primary key,
    student_id  bigint references public.students(student_id) on delete cascade,
    subject_id  bigint references public.subjects(subject_id) on delete cascade,
    timestamp   text not null,           -- ISO-8601, truncated to seconds
    is_present  boolean not null default false,
    created_at  timestamptz default now()
);

create index if not exists idx_attendance_subject on public.attendance_logs(subject_id);
create index if not exists idx_attendance_student on public.attendance_logs(student_id);

-- =========================================================
-- Quick-start policies (PERMISSIVE - for development only).
-- Drop or replace these before going to production.
-- =========================================================
alter table public.teachers          enable row level security;
alter table public.students          enable row level security;
alter table public.subjects          enable row level security;
alter table public.subject_students  enable row level security;
alter table public.attendance_logs   enable row level security;

do $$
begin
    -- teachers
    if not exists (select 1 from pg_policies where tablename = 'teachers' and policyname = 'dev_all') then
        create policy dev_all on public.teachers for all using (true) with check (true);
    end if;
    -- students
    if not exists (select 1 from pg_policies where tablename = 'students' and policyname = 'dev_all') then
        create policy dev_all on public.students for all using (true) with check (true);
    end if;
    -- subjects
    if not exists (select 1 from pg_policies where tablename = 'subjects' and policyname = 'dev_all') then
        create policy dev_all on public.subjects for all using (true) with check (true);
    end if;
    -- subject_students
    if not exists (select 1 from pg_policies where tablename = 'subject_students' and policyname = 'dev_all') then
        create policy dev_all on public.subject_students for all using (true) with check (true);
    end if;
    -- attendance_logs
    if not exists (select 1 from pg_policies where tablename = 'attendance_logs' and policyname = 'dev_all') then
        create policy dev_all on public.attendance_logs for all using (true) with check (true);
    end if;
end $$;
